import pandas as pd

outdir = "/home/daria/Documents/projects/ABC/host_presence/phylofactor"
sts = [131, 95, 73, 69]
presence = pd.read_csv("presence_per_st/presence_per_st_abs.tsv", sep='\t', index_col = 0).transpose()[sts]

def get_subcoms(st):
    subcoms = presence[presence[st]>3].index.to_list()
    return subcoms


rule all:
    input:
        [f"{outdir}/st{st}/{subcom}/tree.pdf" for st in sts for subcom in get_subcoms(st)]

rule phylofactor:
    input:
        tree = "/home/daria/Documents/projects/ABC/host_presence/host_tree/ST{st}_100000000_1000_arc_BD.tre",
        traits = "presence_per_host.tsv"
    output:
        f"{outdir}/st{{st}}/{{subcom}}/tree.pdf"
    params:
        st = lambda wildcards: wildcards.st,
        subcom = lambda wildcards: wildcards.subcom
    conda: "phylofactor"
    resources:
        mem_mb=lambda wildcards, attempt: 20000*attempt
    shell:
        "R < phylofactor.R {params.subcom} {params.st} --no-save"